#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run Bitwarden with nginx and TLS certificates on
# target nodes. Run it like usual executable script:
#
# > ./run-bitwarden.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure Vaultwarden/Bitwarden server
  hosts: bitwarden_servers
  remote_user: root

  roles:
    - { role: jony321.ansible_vaultwarden }
