#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-ca.yml
---
- name: Configure target servers
  hosts: ca
  become: yes
  remote_user: root

  roles:
    - { role: sorrowless.ca, tags: ['ca'] }
