#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run traefik. Run it like
# usual executable script:
#
# > ./run-traefik.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: traefik
  become: yes
  become_user: root

  roles:
    - { role: sorrowless.traefik, tags: ['traefik'] }
