#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run sentry on target nodes. Run it like usual
# executable script:
#
# > ./run-sentry.yml

---
- name: Configure target servers
  hosts: sentry
  become: yes
  remote_user: root

  roles:
    - { role: one_mind.sentry, tags: ['sentry'] }
