---
- name: Deploy personal site to target host
  hosts: sbog_ru_webservers
  remote_user: root

  roles:
    - { role: letsencrypt, tags: ['tls', 'nginx'] }
    - { role: sbog_ru, tags: ['nginx', 'personal'] }
