#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run Bitwarden with nginx and TLS certificates on
# target nodes. Run it like usual executable script:
#
# > ./run-bitwarden.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: bitwardens
  become: yes
  become_user: root

  pre_tasks:
    - name: Ensure nginx installed
      package:
        name: nginx
        state: present

  roles:
    - { role: tls, tags: ['tls', 'nginx'] }
    - { role: nginx, tags: ['nginx'] }

  tasks:
    - name: Ensure needed packages
      package:
        name:
          - docker.io
          - python3-pip
          - python-pip
        state: present
      tags:
        - docker
        - bitwarden

    - name: Ensure latest python Docker SDK
      # In Ubuntu Xenial latest python3-docker sdk version is 1.9, but Ansible
      # 2.8 needed 1.10 at least, so we install in system-wide by pip
      become: yes
      become_user: root
      pip:
        name:
         - docker
         - docker-compose
      tags:
        - pip
        - docker
        - bitwarden

    - name: Ensure docker service is enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker
        - bitwarden

    - name: Ensure bitwarden directories
      file:
        state: directory
        path: "{{ item }}"
        mode: 0750
        owner: root
        group: root
      with_items:
        - /var/bitwarden
      tags:
        - docker
        - bitwarden

    - name: Configure network ranges for docker hosts
      docker_network:
        name: ext_network
        driver_options:
          # Have to be 15 symbols or less
          com.docker.network.bridge.name: bw_bridge
        ipam_config:
          - subnet: 10.10.10.0/24
            gateway: 10.10.10.1
            iprange: 10.10.10.128/25
      tags:
        - docker
        - bitwarden

    - name: Ensure bitwarden docker container
      docker_service:
        state: present
        project_name: bitwarden
        definition:
          version: '2'
          services:
            bitwarden:
              image: "bitwardenrs/server:latest"
              container_name: bitwarden
              ports:
                # host:port
                - "127.0.0.1:8080:80"
              volumes:
                - "/var/bitwarden/:/data"
              environment:
                - YUBICO_CLIENT_ID={{ yubico_client_id }}
                - YUBICO_SECRET_KEY={{ yubico_secret_key }}
                # disable this for the first time
                - SIGNUPS_ALLOWED=false
              hostname: bitwarden
              restart: always
              labels:
                - bitwarden
          networks:
            default:
              external:
                name: ext_network
      tags:
        - docker
        - bitwarden

