#!/usr/bin/env ansible-playbook
#
# Playbook to work with TLS certificates on target nodes. Run
# it like usual executable script:
#
# > ./run-tls.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: tls
  remote_user: root

  roles:
    - { role: tls, tags: ['tls'] }
