---
# In case there is no python symlink in Ubuntu Xenial, you can run this
# playbook by:
#
# ansible-playbook -b run-minimal.yml -e 'ansible_python_interpreter=python3' \
#   -i <inventory_file>
- name: Configure target servers
  hosts: all
  remote_user: root

  roles:
    - { role: pw_policy, tags: ['security'] }
    - { role: server_common, tags: ['common'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: sshd, tags: ['sshd'] }

