---
- name: Deploy personal site to target host
  hosts: websites
  remote_user: root

  roles:
    - { role: tls, tags: ['tls', 'nginx'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: sbog_ru, tags: ['nginx', 'personal'] }
