#!/usr/bin/env -S ansible-playbook --limit mx -e @vars/extra.yaml
#
# This is a playbook to install full-fledged mail server solution based on
# Postfix and Dovecot. Installation itself includes:
# - TLS role to ensure https connection to Uchiwa dashboard
# - MySQL to store virtual mailboxes
# - Postfix
# - Dovecot
# - Rainloop web-interface
#
# Run it like usual executable script:
#
# > ./run-mail.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Update apt cache
  import_playbook: run-apt-update.yml

- name: Get needed TLS certificates
  hosts: mx
  remote_user: root
  roles:
    - { role: tls, tags: ['tls', 'nginx'] }

- name: Install MariaDB
  hosts: mx
  remote_user: root
  roles:
    - { role: mariadb, tags: ['mariadb', 'mysql'] }

- name: Install postfix MTA
  hosts: mx
  remote_user: root
  roles:
    - { role: postfix, tags: ['postfix'] }

- name: Install Nginx for postfixadmin web-interface
  hosts: mx
  remote_user: root
  roles:
    - { role: nginx, tags: ['nginx'] }

- name: Install dovecot MDA
  hosts: mx
  remote_user: root
  roles:
    - { role: dovecot, tags: ['dovecot'] }

- name: Install Rainloop web-client
  hosts: mx
  remote_user: root
  roles:
    - { role: rainloop, tags: ['rainloop'] }
