---
- name: Configure target servers
  hosts: nginx
  remote_user: root

  pre_tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

  roles:
    - { role: letsencrypt, tags: ['tls'] }
    - { role: nginx, tags: ['nginx'] }
