#!/usr/bin/env ansible-playbook
#
# Playbook to install and run backup solution based on rsnapshot on target
# nodes. Additionally it installs apprise to know when backup task was failed
# by sending message about that to Telegram messenger.
# Run it like usual executable script:
#
# > ./run-backup.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure backup
  hosts: backups
  remote_user: root

  roles:
    - { role: rsnapshot, tags: ['backup'] }

- name: Configure backup notifications
  import_playbook: run-apprise.yml

