---
- name: Install and configure Graphite
  hosts: graphite
  remote_user: root
  roles:
    - { role: graphite, tags: [ 'graphite' ] }

- name: Install and configure Grafana
  hosts: grafana
  remote_user: root
  roles:
    - { role: grafana, tags: [ 'grafana' ] }

# To run this, you **MUST** have a group in inventory names
# 'sensu_masters' which will have all Sensu master hosts
# Also remember that you need to allow firewall traffic to the
# Sensu master rabbitmq port
- name: Install and configure Sensu alerting
  hosts: all
  remote_user: root

  roles:
    - { role: sensu, tags: ['sensu'] }

- name: Install and configure Nginx for Uchiwa
  hosts: sensu_masters
  remote_user: root

  pre_tasks:
    - name: Preinstall nginx
      package:
        name: nginx
        state: latest
      tags: nginx

  roles:
    - { role: nginx, tags: ['nginx'] }
    - { role: letsencrypt, tags: ['tls', 'nginx'] }

- name: Configure Sensu hooks
  hosts: all
  remote_user: root
  tasks:
    - name: Allow Sensu to run some hooks with sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      with_items:
        - regex: '^sensu.*systemctl.*'
          line: 'sensu ALL=(ALL) NOPASSWD: /bin/systemctl *'
      tags:
        - sensu
        - sudoers
