---
ansible_host: "{{ vault_ansible_host }}"
ansible_port: "{{ sshd_port }}"
ansible_user: "{{ ansible_common_user }}"
ansible_become: true

# Hosts name
server_common_host:
  dns_hostname: youtrack

iptables:
  host_allowed_tcp_ports: [80, 443, "{{ ansible_port }}"]

domain: example.com

tls_host:
  type: acme
  acme_challenge: standalone
  target_dir: /etc/ssl_certs
  target_key_name: private.pem
  target_cert_name: fullchain.pem
  acme_domains:
    - "youtrack.{{ domain }}"

# Nginx-related vars
nginx_sites:
  jira_http:
    - listen 80
    - server_name {{ tls_host.acme_domains[0] }}
    - return 301 https://$host$request_uri
  jira_https:
    - listen 443 ssl http2
    - server_name {{ tls_host.acme_domains[0] }}
    - access_log  /var/log/nginx/{{ tls_host.acme_domains[0] }}.log
    - error_log  /var/log/nginx/{{ tls_host.acme_domains[0] }}.err.log
    - ssl on
    - ssl_certificate     /etc/ssl_certs/{{ tls_host.acme_domains[0] }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_host.acme_domains[0] }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols       TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - client_max_body_size 15m
    - add_header Strict-Transport-Security max-age=31536000
    - |
      location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 10m;

        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8080;
      }
    - |
      location /api/eventSourceBus {
        proxy_cache off;
        proxy_buffering off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;

        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8080;
      }
