#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-server-common.yml
#
---
- name: Configure iptables
  hosts: iptables

  roles:
    - { role: sorrowless.iptables, tags: ['iptables'] }

  tasks:
    - name: Restart docker
      become: yes
      systemd:
        name: docker
        state: restarted
      when:
        - (iptables.flush_all is defined and iptables.flush_all) or (not iptables.flush_all is defined and iptables_defaults.flush_all)
      tags:
        - iptables
      register: result_restart_docker
      failed_when: "result_restart_docker is failed and 'Could not find the requested service' not in result_restart_docker.msg"
