---
tls_basedir: "{{ tls_host[0].acme_domains[0] }}"
# This name gotten from role defaults
# Bw-related vars
bw_domainname: bw.sbog.org

# Nginx-related vars
nginx_sites:
  "bw.sbog.ru_http":
    - listen 80
    - server_name {{ bw_domainname }}
    - return 301 https://$host$request_uri

  "bw.sbog.ru_https":
    - listen 443 ssl http2
    - server_name {{ bw_domainname }}
    - access_log  /var/log/nginx/{{ bw_domainname }}.log
    - error_log  /var/log/nginx/{{ bw_domainname }}.err.log
    - ssl on
    - ssl_certificate /etc/ssl_certs/{{ bw_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ bw_domainname }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - client_max_body_size 50M
    - add_header Strict-Transport-Security max-age=31536000
    - |
      location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
        proxy_pass http://127.0.0.1:8080;
      }
