---
# Docker config
docker_additional_networks:
  - name: tf_net_public
    driver: overlay
    bridge_name: tf_bridge
    subnet: 10.100.0.0/16
    gateway: 10.100.0.1
    iprange: 10.100.128.0/17
  - name: prom_network
    driver: overlay
    bridge_name: prom_bridge
    subnet: 10.101.0.0/16
    gateway: 10.101.0.1
    iprange: 10.101.128.0/17

docker_live_restore: false
docker_swarm_manager: true
docker_swarm_configure: true

docker_swarm_node_labels:
  traefik: "yes"
