---
docker_services_configurations:
  - stack_name: "ntop"
    swarm_manager_name: router-pc.sbog.org
    tags:
      - "ntop"
      - "services"
      - "ntopng"
    compose:
      services:
        ntopng:
          image: "ntop/ntopng:latest"
          user: root
          networks:
            - host
          command: "--community -d /var/lib/ntopng -i enp3s0 -r 127.0.0.1:6379@0"
          environment:
            - TZ=Etc/UTC
          volumes:
            - /var/lib/ntopng:/var/lib/ntopng
            - /var/lib/ntopng-redis:/var/lib/redis
          deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints: []
            labels: []
      networks:
        host:
          external:
            name: "host"
