---
grafana_docker_image: "grafana/grafana:11.1.3"
grafana_web_host: grafana.sbog.ru
grafana:
  admin_user: admin
  admin_password: PestoPrepesto
grafana_docker_network_name: prom_network
grafana_url: "https://{{ grafana_web_host }}/"
grafana_datasources:
  - name: VictoriaMetrics
    url: http://{{ vmselect_container_name  }}:8481/select/0/prometheus
    type: prometheus
    access: proxy
    isDefault: true

grafana_provisioning_dashboards: []
grafana_ports: []
grafana_stack_name: mon
grafana_swarm_cluster: true
grafana_swarm_manager: router-pc.sbog.org
grafana_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []
  labels:
    - "traefik.enable=true"
    - "traefik.swarm.network={{ grafana_docker_network_name }}"
    - "traefik.http.routers.grafana.rule=Host(`{{ grafana_web_host }}`)"
    - "traefik.http.routers.grafana.tls=true"
    - "traefik.http.routers.grafana.tls.certResolver=acmeDNS"
    - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    - "traefik.http.services.grafana.loadbalancer.sticky.cookie=true"
