---
haproxy_global: |
  global
      log /dev/log local0
      log /dev/log local1 notice
      chroot /var/lib/haproxy
      stats socket /run/haproxy/admin.sock mode 660 level admin
      stats timeout 30s
      user haproxy
      group haproxy
      daemon
      maxconn 200000
      nbproc "{{ [ansible_processor_vcpus, 16] | min }}"
  {% for n in range([ansible_processor_vcpus, 16] | min) %}
      cpu-map {{ n + 1 }} {{ n }}
  {% endfor %}
      ca-base /etc/ssl/certs
      crt-base /etc/ssl/private
      ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
      ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
      tune.ssl.default-dh-param 2048
haproxy_conf: |
  frontend blackbox_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9115 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend blackbox_exporter

  backend blackbox_exporter
      mode http
      timeout server 10m
      server blackbox-exporter 127.0.0.1:9115



  frontend domain_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9222 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend domain_exporter

  backend domain_exporter
      mode http
      timeout server 10m
      server domain-exporter 127.0.0.1:9222



  frontend grok_exporter_auth
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9144 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend grok_exporter_auth

  backend grok_exporter_auth
      mode http
      timeout server 10m
      server grok-exporter-auth 127.0.0.1:9144

  frontend grok_exporter_nginx
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9145 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend grok_exporter_nginx

  backend grok_exporter_nginx
      mode http
      timeout server 10m
      server grok-exporter-nginx 127.0.0.1:9145



  frontend mysqld_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9104 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend mysqld_exporter

  backend mysqld_exporter
      mode http
      timeout server 10m
      server mysqld-exporter 127.0.0.1:9104



  frontend node_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9100 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend node_exporter

  backend node_exporter
      mode http
      timeout server 10m
      server node-exporter 127.0.0.1:9100



  frontend postgres_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9187 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend postgres_exporter

  backend postgres_exporter
      mode http
      timeout server 10m
      server postgres-exporter 127.0.0.1:9187



  frontend scripts_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9273 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend scripts_exporter

  backend scripts_exporter
      mode http
      timeout server 10m
      server scripts-exporter 127.0.0.1:9273



  frontend statsd_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9102 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend statsd_exporter

  backend statsd_exporter
      mode http
      timeout server 10m
      server statsd-exporter 127.0.0.1:9102



  frontend cadvisor_exporter
      mode http
      bind {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:9080 ssl crt /etc/ssl_certs/{{ ansible_host }}/bundle.pem
      http-request redirect scheme https unless { ssl_fc }
      default_backend cadvisor_exporter

  backend cadvisor_exporter
      mode http
      timeout server 10m
      server cadvisor-exporter 127.0.0.1:9080
