---
ansible_host: host  <-- MUST BE CHANGED
ansible_port: 909
ansible_user: deployer
ansible_become: true

iptables:
  host_allowed_tcp_ports: [22, 25, 80, 143, 443, 465, 587, 909, 993, 995, 4190]
  flush_all: True

domain: example.ru
# Let's Encrypt vars
tls_host:
  acme_domains:
    - "mail.{{ domain }}"
    - "pa.mail.{{ domain }}"
    - "smtp.{{ domain }}"
    - "imap.{{ domain }}"
    - "pop.{{ domain }}"
    - "pop3.{{ domain }}"

# Mail vars
mail_domain: "{{ domain }}"
mail_hostname: "mail.{{ domain }}"
mail_ssl_enabled: true
check_policy:
  enabled: true
  address: "127.0.0.1"
  port: 10023
dkim:
  enabled: false
  milter_address: "127.0.0.1"
  milter_port: 8891
spamassassin:
  enabled: false
postfix_db_user: postfix
postfix_db_password: postfixpassword
postfix_db_host: "127.0.0.1"
postfix_db_name: postfix
mysql_port: 3306
mysql_bind_address: "127.0.0.1"
mysql_root_db_pass: mysqlroot
mysql_users:
  - name: postfix
    pass: postfixpassword
    priv: "postfix.*:ALL"
  - name: postfixadmin
    pass: pfxadmpass
    priv: "postfix.*:ALL"
mysql_db:
  - name: postfix
    replicate: no
postfixadmin_db_password: pfxadmpass
postfixadmin_superuser: admin
postfixadmin_superpass: adminpassword
# Dovecot additional vars
mx_hosts:
  - "mail.{{ domain }}"
  - "smtp.{{ domain }}"
  - "imap.{{ domain }}"
