# Iptables rules
---
iptables:
  host_allowed_tcp_ports: [80, 443]
  flush_all: true
  raw_rules:
    - "-A INPUT -p tcp -m multiport --dports 909,54321 -s 34.255.141.66/32 -j ACCEPT -m comment --comment 'VPN-deployment'"
    - "-A INPUT -p tcp -m multiport --dports 909,54321 -s 18.206.2.118/32 -j ACCEPT -m comment --comment 'VPN-US'"
    - "-A INPUT -p tcp -m multiport --dports 909,54321 -s 52.215.11.244/32 -j ACCEPT -m comment --comment 'VPN-IPSec-Ireland-AWS'"
    - "-A INPUT -p tcp -m multiport --dports 909,54321 -s 45.152.113.58/32 -j ACCEPT -m comment --comment 'VPN-IPSec-Ireland-AWS'"
