#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to restart docker on target nodes. Run it like usual executable
# script:
#
# > ./run-minimal.yml
#
- name: Restart docker
  hosts: iptables
  become: yes
  remote_user: root

  tasks:
    - name: Restart docker
      systemd:
        name: docker
        state: restarted
      when:
        - (iptables.flush_all is defined and iptables.flush_all) or (not iptables.flush_all is defined and iptables_defaults.flush_all)
      tags:
        - iptables
      failed_when: false
