---
ansible_ip: 130.61.160.211
ansible_host: ipsec-oc2.sbog.ru
ansible_port: "{{ sshd_port }}"
ansible_user: sbog
ansible_become: true

iptables:
  host_allowed_tcp_ports: [22, 25, 80, 143, 443, 465, 587, 909, 993, 995, 4190, 53589]
  flush_all: False

server_common_host:
  dns_hostname: "sbog.ru-oracle2"
  packages:
    - "{{ server_common_data.packages }}"
    - vim
    - pv
    - python-setuptools

