---
- name: Switch to mitogen for current deployment project
  hosts: localhost

  tasks:
    - name: Set fact with mitogen version
      set_fact:
        mitogen_version: 0.2.8

    - name: Create library directory if it does not exists yet
      file:
        state: directory
        path: ../library
        mode: 0755

    - name: Download mitogen binary
      get_url:
        url: "https://networkgenomics.com/try/mitogen-{{ mitogen_version }}.tar.gz"
        dest: ../library/
        mode: 0644

    - name: Unpack mitogen to library directory
      unarchive:
        src: "../library/mitogen-{{ mitogen_version }}.tar.gz"
        dest: ../library/
        creates: "../library/mitogen-{{ mitogen_version }}"

    - name: Ensure mitogen strategies in ansible config
      lineinfile:
        path: ../ansible.cfg
        line: "strategy_plugins = library/mitogen-{{ mitogen_version }}/ansible_mitogen/plugins/strategy"
        insertafter: '\[defaults\]'
      when: set_local_ansible_config is defined

    - name: Ensure mitogen usage in ansible config
      lineinfile:
        path: ../ansible.cfg
        line: 'strategy = mitogen_linear'
        insertafter: '^strategy_plugins = .*'
      when: set_local_ansible_config is defined
