# Iptables rules
---
iptables:
  host_allowed_udp_ports: [51820]
  host_allowed_tcp_ports: [22, 80, 443, 909]
  flush_all: True
  raw_rules:
    #- "-P INPUT DROP"
    #- "-P FORWARD DROP"
    #- "-P OUTPUT  ACCEPT"

    #- "-F"
    #- "-t nat -F"
    #- "-t mangle -F"

    - "-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment 'accept-anything-already-accepted'"
    - "-A INPUT -i lo -j ACCEPT -m comment --comment 'accept-anything-on-the-loopback-interface'"
    - "-A INPUT -m state --state INVALID -j DROP -m comment --comment 'drop-invalid-packets'"
