---
vpn_bot_image: harbor.oom.ag/library/vpn-bot:v0.5
vpn_bot_api_id: "{{ vault_vpn_bot_api_id }}"
vpn_bot_api_hash: "{{ vault_vpn_bot_api_hash }}"
vpn_bot_client_name: vpn-bot
vpn_bot_token: "{{ vault_vpn_bot_token }}"
vpn_bot_listen_address: 127.0.0.1:8000

vpn_bot_conf_dir: /etc/vpn_bot
vpn_bot_conf: "{{ vault_vpn_bot_conf }}"
