---
tls_basedir: "{{ tls_host[0].acme_domains[0] }}"
# This name gotten from role defaults
site_hostname: sbog.ru
website_domainname: "{{ site_hostname }}"
# This name gotten from role defaults
blog_hostname: blog.sbog.ru
blog_domainname: "{{ blog_hostname }}"
mainsite_hostname: sbog.ru
ya_metrika: "{{ vault_ya_metrika }}"
# Rss-related vars
ttrss_domainname: rss.sbog.ru
ttrss_common_host: "{{ vault_ttrss_common_host }}"
# Bw-related vars
bw_domainname: bw.sbog.ru
# Mail-related vars
mail_domainname: mail.sbog.ru
pa_domainname: "pa.{{ mail_domainname }}"
davical_host: cal.sbog.ru

# Nginx-related vars
nginx_sites:
  "{{ website_domainname }}_http":
    - listen 80
    - server_name {{ website_domainname }} www.{{ website_domainname }}
    - return 301 https://$host$request_uri

  "www.{{ website_domainname }}_https":
    - listen 4443 ssl http2
    - server_name www.{{ website_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - return 301 https://{{ website_domainname }}$request_uri

  "{{ website_domainname }}_https":
    - listen 4443 ssl http2
    - server_name {{ website_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - gzip on
    - charset utf-8
    - client_max_body_size 32m
    - keepalive_timeout 5
    - gzip_types *
    - access_log /var/log/nginx/{{ website_domainname }}.access.log
    - error_log /var/log/nginx/{{ website_domainname }}.error.log
    - root /var/www/{{ website_domainname }}/
    - index index.html index.htm
    - |
      location / {
        try_files $uri $uri/ /index.html;
      }
    - error_page 404 /404.html
    - |
      location = /404.html {
          root   /usr/share/nginx/html;
      }
    - |
      location /doc/ {
          alias /usr/share/doc/;
          autoindex on;
          allow 127.0.0.1;
          deny all;
      }

  "{{ blog_domainname }}_http":
    - listen 80
    - server_name {{ blog_domainname }}
    - return 301 https://$host$request_uri

  "{{ blog_domainname }}_https":
    - listen 4443 ssl http2
    - server_name {{ blog_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - gzip on
    - charset utf-8
    - client_max_body_size 32m
    - keepalive_timeout 5
    - gzip_types *
    - access_log /var/log/nginx/{{ blog_domainname }}.access.log
    - error_log /var/log/nginx/{{ blog_domainname }}.error.log
    - root /var/www/{{ blog_domainname }}/
    - index index.html index.htm
    - |
      location / {
        try_files $uri $uri/ /index.html;
      }
    - error_page 404 /404.html
    - |
      location = /404.html {
          root   /usr/share/nginx/html;
      }
    - |
      location /doc/ {
          alias /usr/share/doc/;
          autoindex on;
          allow 127.0.0.1;
          deny all;
      }

  "{{ ttrss_domainname }}_http":
    - listen 80
    - server_name {{ ttrss_domainname }}
    - return 301 https://$host$request_uri

  "{{ ttrss_domainname }}_https":
    - listen 4443 ssl http2
    - server_name {{ ttrss_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - gzip on
    - charset utf-8
    - client_max_body_size 32m
    - keepalive_timeout 5
    - gzip_types *
    - access_log /var/log/nginx/{{ ttrss_domainname }}.access.log
    - error_log /var/log/nginx/{{ ttrss_domainname }}.error.log
    - root /var/www/ttrss/
    - index index.html index.htm
    - |
      location / {
        index index.php;
        try_files $uri $uri/ /index.php?$args;
      }
    - |
      location /doc/ {
        alias /usr/share/doc/;
        autoindex on;
        allow 127.0.0.1;
        deny all;
      }
    - |
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
      }
    - |
      location ~ /\.ht {
        deny  all;
      }
    - |
      location ^~ /data {
        deny  all;
      }
    - |
      location /favicon.ico {
        log_not_found   off;
        access_log      off;
      }

  "{{ bw_domainname }}_http":
    - listen 80
    - server_name {{ bw_domainname }}
    - return 301 https://$host$request_uri

  "{{ bw_domainname }}_https":
    - listen 4443 ssl http2
    - server_name {{ bw_domainname }}
    - access_log  /var/log/nginx/{{ bw_domainname }}.log
    - error_log  /var/log/nginx/{{ bw_domainname }}.err.log
    - ssl on
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - client_max_body_size 50M
    - add_header Strict-Transport-Security max-age=31536000
    - |
      location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
        proxy_pass http://127.0.0.1:8080;
      }

  "{{ pa_domainname }}_http":
    - listen 80
    - server_name {{ pa_domainname }}
    - return 301 https://$host$request_uri
  "{{ pa_domainname }}_https":
    - listen 4443 ssl
    - server_name {{ pa_domainname }}
    - gzip on
    - gzip_types *
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - root /usr/share/postfixadmin/
    - index index.html index.htm
    - access_log /var/log/nginx/{{ pa_domainname }}.access.log
    - error_log /var/log/nginx/{{ pa_domainname }}.error.log
    - |
      location / {
        index   index.php;
        try_files $uri $uri/ /index.php?$args;
      }
    - |
      location /doc/ {
        alias /usr/share/doc/;
        autoindex on;
        allow 127.0.0.1;
        deny all;
      }
    - |
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
      }
    - |
      location ~ /\.ht {
        deny  all;
      }
    - |
      location ^~ /data {
        deny  all;
      }
    - |
      location /favicon.ico {
        log_not_found   off;
        access_log      off;
      }
  "{{ mail_domainname }}_http":
    - listen 80
    - server_name {{ mail_domainname }}
    - return 301 https://$host$request_uri
  "{{ mail_domainname }}_https":
    - listen 4443 ssl
    - server_name {{ mail_domainname }}
    - gzip on
    - gzip_types *
    - ssl_certificate /etc/ssl_certs/{{ tls_basedir }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ tls_basedir }}/private.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - root /var/www/rainloop/
    - index index.html index.htm
    - access_log /var/log/nginx/{{ mail_domainname }}.access.log
    - error_log /var/log/nginx/{{ mail_domainname }}.error.log
    - client_max_body_size 100M
    - |
      location / {
        index   index.php;
        try_files $uri $uri/ /index.php?$args;
      }
    - |
      location /doc/ {
        alias /usr/share/doc/;
        autoindex on;
        allow 127.0.0.1;
        deny all;
      }
    - |
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
      }
    - |
      location ~ /\.ht {
        deny  all;
      }
    - |
      location ^~ /data {
        deny  all;
      }
    - |
      location /favicon.ico {
        log_not_found   off;
        access_log      off;
      }
  "{{ davical_host }}_http":
    - listen 80
    - server_name {{ davical_host }}
    - return 301 https://$host$request_uri
  "{{ davical_host }}_https":
    - listen 4443 ssl
    - server_name {{ davical_host }}
    - gzip on
    - gzip_types *
    - ssl_certificate /etc/ssl_certs/{{ mail_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ mail_domainname }}/private.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - root /usr/share/davical/htdocs
    - index index.php
    - access_log /var/log/nginx/{{ davical_host }}.access.log
    - error_log /var/log/nginx/{{ davical_host }}.error.log
    - |
      location / {
        rewrite ^/principals/users/(.+)$    https://{{ davical_host }}/caldav.php/$1 break;
        rewrite /.well-known/(.+)$          https://{{ davical_host }}/caldav.php/.well-known/$1 break;
      }
    - |
      location ~ \.php$ {
        try_files $uri =404;
        include /etc/nginx/fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
      }
    - |
      location ~ ^(.+\.php)(.*)$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;

        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

        fastcgi_read_timeout 180;
        fastcgi_buffers 4 256k;
        fastcgi_buffer_size 128k;
      }
    - |
      location ~ /\.ht {
        deny  all;
      }
    - |
      location /favicon.ico {
        log_not_found   off;
        access_log      off;
      }

