---
tls_basedir: "{{ tls_host[0].acme_domains[0] }}"
# This name gotten from role defaults
site_hostname: sbog.ru
website_domainname: "{{ site_hostname }}"
# This name gotten from role defaults
blog_hostname: blog.sbog.ru
blog_domainname: "{{ blog_hostname }}"
mainsite_hostname: sbog.ru
ya_metrika: "{{ vault_ya_metrika }}"
# Rss-related vars
ttrss_domainname: rss.sbog.ru
ttrss_common_host: "{{ vault_ttrss_common_host }}"
# Bw-related vars
bw_domainname: bw.sbog.ru
# Mail-related vars
mail_domainname: mail.sbog.ru
pa_domainname: "pa.{{ mail_domainname }}"
davical_host: cal.sbog.ru

# Nginx-related vars
nginx_sites:
  "sbog.ru_http":
    - listen 80
    - server_name {{ website_domainname }} www.{{ website_domainname }}
    - return 301 https://$host$request_uri

  "www.sbog.ru_https":
    - listen 4443 ssl http2
    - server_name www.{{ website_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ mail_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ mail_domainname }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - return 301 https://{{ website_domainname }}$request_uri

  "sbog.ru_https":
    - listen 4443 ssl http2
    - server_name {{ website_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ mail_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ mail_domainname }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - gzip on
    - charset utf-8
    - client_max_body_size 32m
    - keepalive_timeout 5
    - gzip_types *
    - access_log /var/log/nginx/{{ website_domainname }}.access.log
    - error_log /var/log/nginx/{{ website_domainname }}.error.log
    - root /var/www/{{ website_domainname }}/
    - index index.html index.htm
    - |
      location / {
        try_files $uri $uri/ /index.html;
      }
    - error_page 404 /404.html
    - |
      location = /404.html {
          root   /usr/share/nginx/html;
      }
    - |
      location /doc/ {
          alias /usr/share/doc/;
          autoindex on;
          allow 127.0.0.1;
          deny all;
      }

  "blog.sbog.ru_http":
    - listen 80
    - server_name {{ blog_domainname }}
    - return 301 https://$host$request_uri

  "blog.sbog.ru_https":
    - listen 4443 ssl http2
    - server_name {{ blog_domainname }}
    - ssl_certificate /etc/ssl_certs/{{ mail_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ mail_domainname }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - gzip on
    - charset utf-8
    - client_max_body_size 32m
    - keepalive_timeout 5
    - gzip_types *
    - access_log /var/log/nginx/{{ blog_domainname }}.access.log
    - error_log /var/log/nginx/{{ blog_domainname }}.error.log
    - root /var/www/{{ blog_domainname }}/
    - index index.html index.htm
    - |
      location / {
        try_files $uri $uri/ /index.html;
      }
    - error_page 404 /404.html
    - |
      location = /404.html {
          root   /usr/share/nginx/html;
      }
    - |
      location /doc/ {
          alias /usr/share/doc/;
          autoindex on;
          allow 127.0.0.1;
          deny all;
      }

  "bw.sbog.ru_http":
    - listen 80
    - server_name {{ bw_domainname }}
    - return 301 https://$host$request_uri

  "bw.sbog.ru_https":
    - listen 4443 ssl http2
    - server_name {{ bw_domainname }}
    - access_log  /var/log/nginx/{{ bw_domainname }}.log
    - error_log  /var/log/nginx/{{ bw_domainname }}.err.log
    - ssl on
    - ssl_certificate /etc/ssl_certs/{{ mail_domainname }}/fullchain.pem
    - ssl_certificate_key /etc/ssl_certs/{{ mail_domainname }}/private.pem
    - ssl_dhparam /etc/ssl_certs/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - ssl_session_cache shared:SSL:10m
    - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    - ssl_prefer_server_ciphers   on
    - client_max_body_size 50M
    - add_header Strict-Transport-Security max-age=31536000
    - |
      location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
        proxy_pass http://127.0.0.1:8080;
      }
